dist: xenial
addons:
  apt:
    update: true
    packages:
    - protobuf-c-compiler
    - libprotobuf-c-dev
    - libuv1-dev
language: c
compiler:
  - clang
  - gcc
install: ./autogen.sh
script:
  - git clone https://github.com/DNS-OARC/tinyframe.git
  - cd tinyframe
  - ./autogen.sh
  - ./configure --prefix=$PWD/root
  - make all install
  - cd ..
  - export PKG_CONFIG_PATH=$PWD/tinyframe/root/lib/pkgconfig
  - ./configure --enable-warn-all
  - make dist
  - tar zxvf *.tar.gz
  - cd dnswire-[0-9]*
  - mkdir build
  - cd build
  - ../configure --enable-warn-all
  - make
  - make test
