dist: xenial
addons:
  apt:
    sources:
    - sourceline: 'ppa:dns-oarc/dsc-pr'
    update: true
    packages:
    - protobuf-c-compiler
    - libprotobuf-c-dev
    - libuv1-dev
    - libtinyframe-dev
language: c
compiler:
  - clang
  - gcc
install: ./autogen.sh
script:
  - ./configure --enable-warn-all
  - make dist
  - tar zxvf *.tar.gz
  - cd dnswire-[0-9]*
  - mkdir build
  - cd build
  - ../configure --enable-warn-all
  - make
  - make test
  - cat src/test/test*.sh.log
